name: Add Security Headers

on:
  push:
    branches: [ main ]

jobs:
  security_headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create _headers file
        run: |
          echo "/*" > _headers
          echo "  X-Frame-Options: DENY" >> _headers
          echo "  X-Content-Type-Options: nosniff" >> _headers
          echo "  X-XSS-Protection: 1; mode=block" >> _headers
          echo "  Content-Security-Policy: default-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com https://fonts.gstatic.com https://www.googletagmanager.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://www.googletagmanager.com;" >> _headers
          echo "  Referrer-Policy: strict-origin-when-cross-origin" >> _headers
          echo "  Strict-Transport-Security: max-age=31536000; includeSubDomains" >> _headers
          echo "  Permissions-Policy: camera=(), microphone=(), geolocation=()" >> _headers
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          clean: false
